Delete blacklisted token after 1 month
M-Muaz-Shoukat/todo-app pull request #12
Opened 2024-06-13 14:26 UTC by M-Muaz-Shoukat

2024-06-13 14:49 UTC, hammadhussaiin requested changes

2024-06-13 14:49 UTC, hammadhussaiin commented on todo_list/settings.py
> +    'flush_blacklisted_token_every_minute': {
Wrong name. We are not deleting every minute.

2024-06-13 14:49 UTC, hammadhussaiin commented on todo_list_app/tasks.py
> +    call_command('flushexpiredtokens')
This is how we call a management command programatically. This command would delete every token but if we want to move these tokens somewhere else or if we need to delete for all users except the admin? How would this be possible?

2024-06-13 18:23 UTC, M-Muaz-Shoukat commented on todo_list_app/tasks.py
> +    call_command('flushexpiredtokens')
flushexpiredtokens command will only delete those tokens which are expired not all tokens in this way we have no need to keep tokens somewhere else as once token expired it is of no use anyway
same goes for admin token it wouldn't delete until it expires

2024-06-14 13:02 UTC, m-shayan-ahmad approved these changes

2024-06-14 13:02 UTC, merged