Testing
M-Muaz-Shoukat/todo-app pull request #14
Opened 2024-06-14 13:56 UTC by M-Muaz-Shoukat

Added testing for Task , Catgory, Reminder, user   ->> Models, Apis

2024-06-20 14:01 UTC, m-shayan-ahmad requested changes

2024-06-20 14:01 UTC, m-shayan-ahmad commented on todo_list_app/tests/test_auth_apis.py
> +class TestAuthAPI(TestCase):
1. `setUp` should only set up objects or functions required by any test. Any API calls or processing that is part of the test should be in the test itself or if it's common among more than one test you can create a helper private function something like `def _register_user(data)`.
2. How to mock or patch a function and an object to get the return value of it.
3. `auth` is just authentication of user and registration is a separate process.
4. Update folder structure and keep directories and files inside the `tests` directory the same as it is outside. We can rename them to show that they are tests either by prefixing or postfixing the test keyword.

2024-06-21 12:23 UTC, m-shayan-ahmad reviewed
1. Update folder structure in tests
2. Move common attributes to setUp like OTP code
3. How to mock a class function?
4. How to mock a global object?
5. How to mock a class attribute?
6. How to check the return value of a mocked function?
7. How to check what's being passed inside a mocked function?
8. How to check how many calls have been made for a mocked function?

2024-06-24 12:00 UTC, M-Muaz-Shoukat commented
Mock Class Function: @patch(Class_Name, 'funtion_name', return_value=...)
Mock Global Object: @patch('module_name.global_object_name', return_value=...)
Mock Class Attribute: @patch(Class_Name, 'attribute_name', return_value=...)
Return Value of mock function: function_name()
Check argument of mock function: function_name. call_args
Check count of mocked function calls: function_name.call_count

2024-06-27 08:10 UTC, merged